# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2022 Victor Eijkhout
####
#### makefile for Advert/Branding project
####
################################################################

PROGRAMS = advert

LANGUAGE = CXX
include ../Make.inc
CPPSTANDARD = 17

RUNS =

RUNS += run_advert
run_advert : advert
	@./advert

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
