# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2023 Victor Eijkhout
####
################################################################

PROGRAMS = arraycopy
WRONGS = 

LANGUAGE = CXX
include ../Make.inc
CPPSTANDARD = 20
#OPTIONS = -pg
## INCLUDES = -I${LMOD_RANGEV3_INC}
## MODULES = rangev3

RUNS =

.PHONY: ${RUNS}

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
