# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017 Victor Eijkhout
####
################################################################

PROGRAMS = collatz collatzclass collatzrecord \
    sumsquares factspace fibomemo

LANGUAGE = CXX
include ../Make.inc
include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
