# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2019-2023 Victor Eijkhout
####
#### test examples
####
################################################################

PROGRAMS =
# this stuff may compile or not
WRONGS = soldier starnoname array randclass cursor enum pass1714

LANGUAGE = CXX
include ../Make.inc

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
