# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2019-2020 Victor Eijkhout
####
#### gdb examples
####
################################################################

PROGRAMS = hello root assert

include ../Make.inc
LANGUAGE = CXX
OPTLEVEL = 0

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
