# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2021 Victor Eijkhout
####
################################################################

PROGRAMS = poly_eval poly_mat
WRONG = 

LANGUAGE = CXX
include ../Make.inc

RUNS = 

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
