# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2019 Victor Eijkhout
####
#### makefile BMP writing
####
################################################################

PROGRAMS = bmp

LANGUAGE = CXX
include ../Make.inc

.PHONY: run_bmp
run_bmp : bmp
	@./bmp

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
