# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2021 Victor Eijkhout
####
################################################################

PROGRAMS = size storage

LANGUAGE = F
include ../Make.inc

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
