# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2022 Victor Eijkhout
####
#### makefile for dynamic programming
####
################################################################

PROGRAMS = menu

LANGUAGE = CXX
include ../Make.inc

RUNS =

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
