# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2021 Victor Eijkhout
####
#### header examples
####
################################################################

PROGRAMS =
WRONGS = main
main_objects = func.cxx

LANGUAGE = CXX
include ../Make.inc
include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
