# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017 Victor Eijkhout
####
################################################################

PROGRAMS = hello hello34 hellopi helloin helloinwhat

LANGUAGE = CXX
include ../Make.inc

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
