# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2021 Victor Eijkhout
####
#### Makefile for value routines
####
################################################################

PROGRAMS = rvalueconstruct rvaluefun

LANGUAGE = CXX
include ../Make.inc
CPPSTANDARD = 17

##
## regression runs
##
RUNS =

# .PHONY: run_rvalue
# RUNS += run_rvalue
# run_rvalue : rvalue
# 	@./rvalue

include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
