# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017 Victor Eijkhout
####
#### spherical : exercises based on the Spherical Cow book
####
################################################################

PROGRAMS = cobbler

LANGUAGE = CXX
include ../Make.inc
include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
