# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
#### copyright 2017-2020 Victor Eijkhout
####
#### Makefile for infectuous disease simulation in Julia
####
################################################################

.PHONY: info
info ::

PROGRAMS = \
    infectfunction

LANGUAGE = J
include ../Make.inc

RUNS = 
include ../../makefiles/Make.clean
