# -*- makefile -*-
################################################################
####
#### This makefile is part of the course
#### Introduction to Scientific Programming in C++ and Fortran
#### by Victor Eijkhout (eijkhout@tacc.utexas.edu)
####
#### copyright 2020 Victor Eijkhout
####
#### static arrays
####
################################################################

PROGRAMS = init

LANGUAGE = CXX
include ../Make.inc
CPPSTANDARD = 2a
include ../../makefiles/Make.cmake
include ../../makefiles/Make.clean
